brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy  # put into notes that we need include for these admin paths
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")),  # add to notes how this works - we need to do this to path to each app's urls.py file

    path("", RedirectView.as_view(url=reverse_lazy("todos:list_todos")), name="home")

]

todos/urls.py
from django.urls import path  # might as well put this entire file into notes, it is easy to forget

from todos.views import (

    TodoListView,
    TodoDetailView,
    CreateNewListView,

)

app_name = "todos"


urlpatterns= [

    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("new/", CreateNewListView.as_view(), name="create_todolist"),

]

todos/models.py
from asyncio import tasks
from tkinter import CASCADE
from django.db import models

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)   # add this to notes
    created_on = models.DateTimeField(auto_now_add=True)    # add this to notes

    def __str__(self):       # add this to notes
        return self.name
    

class TodoItem(models.Model):
    task =  models.CharField(max_length=100)
    due_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)  # allows field to be empty - add this to notes
    is_completed = models.BooleanField(default=False)  # by default when creating the item this is false
    list = models.ForeignKey("TodoList", related_name = "items", on_delete=models.CASCADE)  # add to notes

    def __str__(self):
        return self.task
    

todos/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView  # put these imports for all class views in notes
from django.views.generic.edit import CreateView

from todos.models import TodoList, TodoItem

# Create your views here.

class TodoListView(ListView):
    model = TodoList    # put this in notes, for class views is model not context
    template_name = "todos/list.html" # also put this in notes for funsies
    context_object_name = "todo_list" # change the default context name to this



class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"
    context_object_name = "todo_detail"


class CreateNewListView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    context_object_name = "create_todolist"
    fields = ['name']
    success_url = reverse_lazy("todos:show_todolist")

    def get_success_url(self):
        return reverse_lazy("todos:show_todolist", kwargs={'pk': self.object.pk})

todos/templates/todos/detail.html
{% load static %}
<!DOCTYPE HTL>
<html>
	<head> </head>
	<body>
		<main>
			<div>
				<table>
					<thead>
						<tr>
							<th>{{todo_detail.name}}</th>
						</tr>
					</thead>
					<tbody>
						{% for a_task in todo_detail.items.all %}
						<tr>
							<td>{{ a_task.task }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</main>
	</body>
</html>

todos/templates/todos/list.html
{% load static %}
<!DOCTYPE HTL>
<html>
	<head> </head>
	<body>
		<main>
			<div>
				<h1>My Lists</h1>
                <p><a href="{% url "todos:create_todolist"  %}"> Create a new list </a></p>
				<table>
					<thead>
						<tr>
							<th>Name</th>
							<th>Number of Items</th>
						</tr>
					</thead>
					<tbody>
						{% for names in todo_list.all %}
						<tr>
							<td>
                                <a href="{% url "todos:show_todolist" names.pk %}">    
                                {{ names.name }} </a>
                            </td>
                            <td>
                                &nbsp&nbsp&nbsp&nbsp&nbsp{{ names.items.all|length }} <!-- names.items.all length filter should work-->
                            </td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</main>
	</body>
</html>

todos/templates/todos/new.html
{% load static %}
<!DOCTYPE HTL>
<html>
	<head> </head>
	<body>
		<main>
			<div>
				<h1>Create a new To-do list</h1>
			</div>
			<form method="post">
				<div>
					{% csrf_token %}{{form.as_p}}
					<button>Submit</button>
				</div>
			</form>
		</main>
	</body>
</html>